name: dbcrypt
version: 1.0.0-alpha
author: Erlantz Oniga <erlantz8@gmail.com>
description: A port of jBCrypt to Dart
homepage: https://github.com/Erly/dbcrypt
environment:
  sdk: '>=1.24.0 <3.0.0'
dev_dependencies:
  benchmark_harness: '>=1.0.2 <2.0.0'
  test: '^0.12.0'
