name:  dbcrypt
author: Erlantz Oniga <erlantz8@gmail.com>
homepage: https://github.com/Erly/dbcrypt
version: 0.1.0
description:  A port of JBCrypt to Dart

dependencies:
  unittest: any
  benchmark_harness: ">=1.0.2 <2.0.0"
  drandom:
    git: https://github.com/Erly/DRandom.git