name: dbcrypt
version: 0.1.3+1
author: Erlantz Oniga <erlantz8@gmail.com>
description: A port of JBCrypt to Dart
homepage: https://github.com/Erly/dbcrypt
dependencies:
  unittest: any
  benchmark_harness: '>=1.0.2 <2.0.0'
  drandom: any
#    git: https://github.com/Erly/DRandom.git
